//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Mvc_Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Branslar
    {
        public byte Bransid { get; set; }
        public string BransAD { get; set; }
    }
}
