//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Mvc_Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hastalar
    {
        public short Hastaid { get; set; }
        public string HastaAd { get; set; }
        public string HastaSoyad { get; set; }
        public string HastaTC { get; set; }
        public string HastaTelefon { get; set; }
        public string HastaSifre { get; set; }
        public string HastaCinsiyet { get; set; }
    }
}
